she_codes_news/users/urls.py
from django.urls import path 
from .views import CreateAccountView, UserListView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('create/', CreateAccountView.as_view(), name='createAccount'),
    path('profile/', UserListView.as_view(), name = 'list'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name = 'profile'),
    path('profile/<str:slug>/',UserProfileView.as_view(), name = 'profile'),
]

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

    

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic

from .models import CustomUser
from .forms import CustomUserCreationForm


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'users/createAccount.html'


class UserProfileView(generic.DetailView):
    model = CustomUser
    slug_field = "username"


class UserListView(generic.ListView):
    model = CustomUser

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}

<h2> Create Account </h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type = "submit">Create Account</button>
</form>
{%endblock content%}

she_codes_news/users/templates/users/customuser_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ customuser.username }}</h2>

<div>
    {% for story in customuser.stories.all %}
      {% include 'news/storyCard.html' %}
    {% endfor %}
</div>

{% endblock content %}

she_codes_news/users/templates/users/customuser_list.html
{% extends 'base.html' %}

{% block content %}

<h2>Authors</h2>

<div>
    {% for user in customuser_list %}
    <h4><a href="{% url 'users:profile' user.id %}">{{ user.username }}</a></h4>
        Stories written: {{user.stories.count}}
    {% endfor %}
</div>

{% endblock content %}