she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name= 'story'),
    path('<int:pk>/edit/', views.StoryEditView.as_view(), name= 'storyEdit'),
    path('<int:pk>/delete/', views.StoryDeleteView.as_view(), name= 'storyDelete'),
    path('<int:pk>/like/', views.like, name="like"),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="stories"
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.CharField(max_length=500, null=True, blank=True)
    favourited_by = models.ManyToManyField(
        User, related_name= "favourites", blank=True, null=True
        )

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image']
        widgets = {
            'pub_date': forms.DateTimeInput(format=('%d%m/%Y %H:%M'), 
            attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }

she_codes_news/news/views.py
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from .models import NewsStory
from .forms import StoryForm
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by("-pub_date")[:4]
        context['all_stories'] = NewsStory.objects.all().order_by("-pub_date")
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'
    
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    # context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class StoryEditView(LoginRequiredMixin, generic.UpdateView):
    model = NewsStory
    fields = ['title', 'pub_date', 'content', 'image']

    def get_success_url(self) -> str:
        return reverse_lazy('news:story', kwargs={'pk':self.kwargs['pk']})

    def get_queryset(self):
        qs = super().get_queryset()
        # if not self.request.user.is_authenticated:
        #     raise qs.model.DoesNotExist
        # qs = qs.filter(author=self.request.user)
        return qs.filter(author=self.request.user)

class StoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = NewsStory
    success_url = reverse_lazy('news:index')

    def get_queryset(self):
        # filter to only allow to author to delete own story
        qs = super().get_queryset()
        return qs.filter(author=self.request.user)


    ''' when given a pk for a newsstory, add the suer to like, or if exists, remove the user'''
@login_required
def like(request, pk):
    news_story = get_object_or_404(NewsStory, pk=pk)
    if news_story.favourited_by.filter(username=request.user.username).exists():
        news_story.favourited_by.remove(request.user)
    else:
        news_story.favourited_by.add(request.user)
    return redirect(reverse_lazy('news:story', kwargs={'pk':pk}))

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% block content %}

{% if request.user.is_authenticated %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% else %}
<br>
<strong> Login to create an article </strong>

{% endif %}
{% endblock %}

she_codes_news/news/templates/news/index.html
    {% extends "base.html" %}
    {% load static %}

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content%}

    <div>
        {% if user.is_authenticated %}
            <a href="{% url 'news:newStory' %}">Write New Story</a>
        {% endif %}
    </div>

    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include './storyCard.html' with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% comment %} <p>{{ story.title }}</p> {% endcomment %}
                {% include './storyCard.html' with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>



    {% endblock %}

she_codes_news/news/templates/news/newsstory_confirm_delete.html
{% extends 'base.html' %}


{% block content %}

<h1> you wanna delete? <h1>

<h2> {{ newsstory.title }} </h2>
<p> {{ newsstory.content }} </p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Yes I am Sure">
    </form>
  </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/newsstory_form.html
{% extends 'base.html' %}


{% block content %}

<h1> Edit </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel='stylesheet' type='text/css' href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
  <h2>{{ story.title }}</h2>
  <h4>{{ story.author }}</h4>
  <div id="story-content">
    <img src="{{ story.image }}" />
    {{ story.content|linebreaks }}
  </div>
</div>
  {% if story.favourited_by.count %}
    Liked By: {{ story.favourited_by.count }} user{{story.favourited_by.count|pluralize:"s"}}
    ({% for user in story.favourited_by.all %}{{ user.username }}  {% endfor %})
  {% endif %}
  <a href="{% url 'news:like' story.id %}"><button>{% if request.user in story.favourited_by.all %} Unlike {% else %} Like {% endif %} </button>
  <br>
  <a href="{% url 'news:storyEdit' story.id %}"><button>Edit</button>
  <br><br>
  <a href="{% url 'news:storyDelete' story.id %}"><button>Delete</button>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        <img src="{{ story.image }}">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>Published on: {{ story.pub_date|date:'d M y' }}</h4>
        </div>
    </a>
</div>